### ISSUE TITLE
add user directly into space without his confirmation( just send mail that he was put in that space)

### ISSUE THREAD

**Issue by alupoaiemircea** [AssistOS-AI/assistos-workspace#211]

**Comment by Koroem** [comment]
**Nu se poate face elegant**

userul poate fi invitat in mai multe spatii inainte sa aiba cont
si fiind dubla referinta intre fisierul de user si fisierul de spatiu,trb creat un fisier al userului inainte sa aiba cont propriu zis
si sa-i creez userIdul 
si ca sa fie mentinut sistemul de invite cu timeout ar trb sa merg prin toate fisierele de spatiu in care a fost adaugat si sa-l sterg dupa un interval pre-setat
si ca userul sa ajunga la aplicatie oricum trb sa aiba un buton clickable pe email care ar trb apasat, deci nu ar fi nici o diferenta
pe partea de UX dpdv al rapiditatii. 

Sugestie: Daca userul nu are cont pastrat sistemul vechi, daca are cont, adaugat direct in spatiu si trimit email instiintare
