### ISSUE TITLE
la proof reader lipseste bara de separare

### ISSUE THREAD

**Issue by LuciaEsanu** [AssistOS-AI/assistos-workspace#5]
![Image](https://github.com/AssistOS-AI/assistos-workspace/assets/126072729/9c6aa8b0-b082-4924-b4a7-691d8fab49a0)

**Comment by Koroem** [comment]
![Image](https://github.com/AssistOS-AI/assistos-workspace/assets/79149799/51f80ca8-cc96-4e1c-b86d-8a4b62aa5a55)
